// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxMqGP2FOsTcHnLzVEdtp-j8yIle0PTlo',
    appId: '1:967199687604:web:acef7cc1a0a692754628e1',
    messagingSenderId: '967199687604',
    projectId: 'thinkandslide',
    authDomain: 'thinkandslide.firebaseapp.com',
    storageBucket: 'thinkandslide.firebasestorage.app',
    measurementId: 'G-SXK90VHJZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDksrQBZAxfA3ve1H0tEOT3lIl00oMvHrU',
    appId: '1:967199687604:android:a9ae3981aca118654628e1',
    messagingSenderId: '967199687604',
    projectId: 'thinkandslide',
    storageBucket: 'thinkandslide.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8ca1lqY6W5DJ-YP0yKORkUfjOI4qV4LQ',
    appId: '1:967199687604:ios:247a2d8bc7db33b44628e1',
    messagingSenderId: '967199687604',
    projectId: 'thinkandslide',
    storageBucket: 'thinkandslide.firebasestorage.app',
    iosBundleId: 'com.example.thinkAndSlide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8ca1lqY6W5DJ-YP0yKORkUfjOI4qV4LQ',
    appId: '1:967199687604:ios:247a2d8bc7db33b44628e1',
    messagingSenderId: '967199687604',
    projectId: 'thinkandslide',
    storageBucket: 'thinkandslide.firebasestorage.app',
    iosBundleId: 'com.example.thinkAndSlide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxMqGP2FOsTcHnLzVEdtp-j8yIle0PTlo',
    appId: '1:967199687604:web:eb1932195969938c4628e1',
    messagingSenderId: '967199687604',
    projectId: 'thinkandslide',
    authDomain: 'thinkandslide.firebaseapp.com',
    storageBucket: 'thinkandslide.firebasestorage.app',
    measurementId: 'G-VNE74GJTK0',
  );
}
